import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <div className="min-h-screen h-full flex flex-col bg-brand-light overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" 
        content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='min-w-full text-gray-800 py-14 px-4 md:px-0'>
        <div className='flex items-center container mx-auto max-w-5xl justify-betwwen h-full'>
          {/*logo*/}
          
        </div>
      </header>
    </div>
  )
}
